# Generated by Django 4.2.16 on 2024-10-26 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="age",
            field=models.IntegerField(
                null=True, validators=[django.core.validators.MinValueValidator(16)]
            ),
        ),
    ]
