# Generated by Django 4.2.16 on 2024-10-22 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="age",
            field=models.IntegerField(
                default=20, validators=[django.core.validators.MinValueValidator(16)]
            ),
            preserve_default=False,
        ),
    ]
