# Generated by Django 4.2.16 on 2024-11-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
